// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package org.bdawg.open_audio;

public final class OpenAudioProtos {
  private OpenAudioProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientCommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .open_audio.ClientCommand.ClientAction client_action = 1;
    /**
     * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
     */
    boolean hasClientAction();
    /**
     * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
     */
    org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction getClientAction();

    // optional int32 new_volume = 2;
    /**
     * <code>optional int32 new_volume = 2;</code>
     */
    boolean hasNewVolume();
    /**
     * <code>optional int32 new_volume = 2;</code>
     */
    int getNewVolume();

    // optional int64 timestamp = 3;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();

    // optional .open_audio.PlayItem item = 4;
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    boolean hasItem();
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    org.bdawg.open_audio.OpenAudioProtos.PlayItem getItem();
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder getItemOrBuilder();
  }
  /**
   * Protobuf type {@code open_audio.ClientCommand}
   */
  public static final class ClientCommand extends
      com.google.protobuf.GeneratedMessage
      implements ClientCommandOrBuilder {
    // Use ClientCommand.newBuilder() to construct.
    private ClientCommand(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClientCommand(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClientCommand defaultInstance;
    public static ClientCommand getDefaultInstance() {
      return defaultInstance;
    }

    public ClientCommand getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClientCommand(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction value = org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                clientAction_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              newVolume_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 34: {
              org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = item_.toBuilder();
              }
              item_ = input.readMessage(org.bdawg.open_audio.OpenAudioProtos.PlayItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(item_);
                item_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ClientCommand_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ClientCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bdawg.open_audio.OpenAudioProtos.ClientCommand.class, org.bdawg.open_audio.OpenAudioProtos.ClientCommand.Builder.class);
    }

    public static com.google.protobuf.Parser<ClientCommand> PARSER =
        new com.google.protobuf.AbstractParser<ClientCommand>() {
      public ClientCommand parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClientCommand(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClientCommand> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code open_audio.ClientCommand.ClientAction}
     */
    public enum ClientAction
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PLAY = 0;</code>
       */
      PLAY(0, 0),
      /**
       * <code>PAUSE = 1;</code>
       */
      PAUSE(1, 1),
      /**
       * <code>STOP = 2;</code>
       */
      STOP(2, 2),
      /**
       * <code>VOLUME = 3;</code>
       */
      VOLUME(3, 3),
      /**
       * <code>DOWNLOAD = 4;</code>
       */
      DOWNLOAD(4, 4),
      ;

      /**
       * <code>PLAY = 0;</code>
       */
      public static final int PLAY_VALUE = 0;
      /**
       * <code>PAUSE = 1;</code>
       */
      public static final int PAUSE_VALUE = 1;
      /**
       * <code>STOP = 2;</code>
       */
      public static final int STOP_VALUE = 2;
      /**
       * <code>VOLUME = 3;</code>
       */
      public static final int VOLUME_VALUE = 3;
      /**
       * <code>DOWNLOAD = 4;</code>
       */
      public static final int DOWNLOAD_VALUE = 4;


      public final int getNumber() { return value; }

      public static ClientAction valueOf(int value) {
        switch (value) {
          case 0: return PLAY;
          case 1: return PAUSE;
          case 2: return STOP;
          case 3: return VOLUME;
          case 4: return DOWNLOAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientAction>() {
              public ClientAction findValueByNumber(int number) {
                return ClientAction.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.ClientCommand.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientAction[] VALUES = values();

      public static ClientAction valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ClientAction(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:open_audio.ClientCommand.ClientAction)
    }

    private int bitField0_;
    // optional .open_audio.ClientCommand.ClientAction client_action = 1;
    public static final int CLIENT_ACTION_FIELD_NUMBER = 1;
    private org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction clientAction_;
    /**
     * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
     */
    public boolean hasClientAction() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
     */
    public org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction getClientAction() {
      return clientAction_;
    }

    // optional int32 new_volume = 2;
    public static final int NEW_VOLUME_FIELD_NUMBER = 2;
    private int newVolume_;
    /**
     * <code>optional int32 new_volume = 2;</code>
     */
    public boolean hasNewVolume() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 new_volume = 2;</code>
     */
    public int getNewVolume() {
      return newVolume_;
    }

    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional .open_audio.PlayItem item = 4;
    public static final int ITEM_FIELD_NUMBER = 4;
    private org.bdawg.open_audio.OpenAudioProtos.PlayItem item_;
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    public boolean hasItem() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    public org.bdawg.open_audio.OpenAudioProtos.PlayItem getItem() {
      return item_;
    }
    /**
     * <code>optional .open_audio.PlayItem item = 4;</code>
     */
    public org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder getItemOrBuilder() {
      return item_;
    }

    private void initFields() {
      clientAction_ = org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction.PLAY;
      newVolume_ = 0;
      timestamp_ = 0L;
      item_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, clientAction_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, newVolume_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, item_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, clientAction_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, newVolume_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, item_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ClientCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bdawg.open_audio.OpenAudioProtos.ClientCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code open_audio.ClientCommand}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bdawg.open_audio.OpenAudioProtos.ClientCommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ClientCommand_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ClientCommand_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bdawg.open_audio.OpenAudioProtos.ClientCommand.class, org.bdawg.open_audio.OpenAudioProtos.ClientCommand.Builder.class);
      }

      // Construct using org.bdawg.open_audio.OpenAudioProtos.ClientCommand.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientAction_ = org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction.PLAY;
        bitField0_ = (bitField0_ & ~0x00000001);
        newVolume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (itemBuilder_ == null) {
          item_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ClientCommand_descriptor;
      }

      public org.bdawg.open_audio.OpenAudioProtos.ClientCommand getDefaultInstanceForType() {
        return org.bdawg.open_audio.OpenAudioProtos.ClientCommand.getDefaultInstance();
      }

      public org.bdawg.open_audio.OpenAudioProtos.ClientCommand build() {
        org.bdawg.open_audio.OpenAudioProtos.ClientCommand result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bdawg.open_audio.OpenAudioProtos.ClientCommand buildPartial() {
        org.bdawg.open_audio.OpenAudioProtos.ClientCommand result = new org.bdawg.open_audio.OpenAudioProtos.ClientCommand(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientAction_ = clientAction_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.newVolume_ = newVolume_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (itemBuilder_ == null) {
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bdawg.open_audio.OpenAudioProtos.ClientCommand) {
          return mergeFrom((org.bdawg.open_audio.OpenAudioProtos.ClientCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bdawg.open_audio.OpenAudioProtos.ClientCommand other) {
        if (other == org.bdawg.open_audio.OpenAudioProtos.ClientCommand.getDefaultInstance()) return this;
        if (other.hasClientAction()) {
          setClientAction(other.getClientAction());
        }
        if (other.hasNewVolume()) {
          setNewVolume(other.getNewVolume());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasItem()) {
          mergeItem(other.getItem());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bdawg.open_audio.OpenAudioProtos.ClientCommand parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bdawg.open_audio.OpenAudioProtos.ClientCommand) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .open_audio.ClientCommand.ClientAction client_action = 1;
      private org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction clientAction_ = org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction.PLAY;
      /**
       * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
       */
      public boolean hasClientAction() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction getClientAction() {
        return clientAction_;
      }
      /**
       * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
       */
      public Builder setClientAction(org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        clientAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .open_audio.ClientCommand.ClientAction client_action = 1;</code>
       */
      public Builder clearClientAction() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientAction_ = org.bdawg.open_audio.OpenAudioProtos.ClientCommand.ClientAction.PLAY;
        onChanged();
        return this;
      }

      // optional int32 new_volume = 2;
      private int newVolume_ ;
      /**
       * <code>optional int32 new_volume = 2;</code>
       */
      public boolean hasNewVolume() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 new_volume = 2;</code>
       */
      public int getNewVolume() {
        return newVolume_;
      }
      /**
       * <code>optional int32 new_volume = 2;</code>
       */
      public Builder setNewVolume(int value) {
        bitField0_ |= 0x00000002;
        newVolume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 new_volume = 2;</code>
       */
      public Builder clearNewVolume() {
        bitField0_ = (bitField0_ & ~0x00000002);
        newVolume_ = 0;
        onChanged();
        return this;
      }

      // optional int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .open_audio.PlayItem item = 4;
      private org.bdawg.open_audio.OpenAudioProtos.PlayItem item_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bdawg.open_audio.OpenAudioProtos.PlayItem, org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder, org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder> itemBuilder_;
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public boolean hasItem() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.PlayItem getItem() {
        if (itemBuilder_ == null) {
          return item_;
        } else {
          return itemBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public Builder setItem(org.bdawg.open_audio.OpenAudioProtos.PlayItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          item_ = value;
          onChanged();
        } else {
          itemBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public Builder setItem(
          org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          item_ = builderForValue.build();
          onChanged();
        } else {
          itemBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public Builder mergeItem(org.bdawg.open_audio.OpenAudioProtos.PlayItem value) {
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              item_ != org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance()) {
            item_ =
              org.bdawg.open_audio.OpenAudioProtos.PlayItem.newBuilder(item_).mergeFrom(value).buildPartial();
          } else {
            item_ = value;
          }
          onChanged();
        } else {
          itemBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance();
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder getItemBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getItemFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder getItemOrBuilder() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilder();
        } else {
          return item_;
        }
      }
      /**
       * <code>optional .open_audio.PlayItem item = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bdawg.open_audio.OpenAudioProtos.PlayItem, org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder, org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bdawg.open_audio.OpenAudioProtos.PlayItem, org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder, org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder>(
                  item_,
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:open_audio.ClientCommand)
    }

    static {
      defaultInstance = new ClientCommand(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:open_audio.ClientCommand)
  }

  public interface PlayItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes item_bytes = 1;
    /**
     * <code>optional bytes item_bytes = 1;</code>
     */
    boolean hasItemBytes();
    /**
     * <code>optional bytes item_bytes = 1;</code>
     */
    com.google.protobuf.ByteString getItemBytes();

    // optional string item_id = 2;
    /**
     * <code>optional string item_id = 2;</code>
     */
    boolean hasItemId();
    /**
     * <code>optional string item_id = 2;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>optional string item_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();

    // optional string item_uri = 3;
    /**
     * <code>optional string item_uri = 3;</code>
     */
    boolean hasItemUri();
    /**
     * <code>optional string item_uri = 3;</code>
     */
    java.lang.String getItemUri();
    /**
     * <code>optional string item_uri = 3;</code>
     */
    com.google.protobuf.ByteString
        getItemUriBytes();

    // optional bytes torrent_bytes = 4;
    /**
     * <code>optional bytes torrent_bytes = 4;</code>
     */
    boolean hasTorrentBytes();
    /**
     * <code>optional bytes torrent_bytes = 4;</code>
     */
    com.google.protobuf.ByteString getTorrentBytes();

    // optional .open_audio.PlayItem.PlayItemType play_type = 5;
    /**
     * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
     */
    boolean hasPlayType();
    /**
     * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
     */
    org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType getPlayType();
  }
  /**
   * Protobuf type {@code open_audio.PlayItem}
   */
  public static final class PlayItem extends
      com.google.protobuf.GeneratedMessage
      implements PlayItemOrBuilder {
    // Use PlayItem.newBuilder() to construct.
    private PlayItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayItem defaultInstance;
    public static PlayItem getDefaultInstance() {
      return defaultInstance;
    }

    public PlayItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              itemBytes_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              itemId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              itemUri_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              torrentBytes_ = input.readBytes();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();
              org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType value = org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(5, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                playType_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_PlayItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_PlayItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bdawg.open_audio.OpenAudioProtos.PlayItem.class, org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayItem> PARSER =
        new com.google.protobuf.AbstractParser<PlayItem>() {
      public PlayItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayItem> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code open_audio.PlayItem.PlayItemType}
     */
    public enum PlayItemType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BYTES = 0;</code>
       */
      BYTES(0, 0),
      /**
       * <code>INET_URI = 1;</code>
       */
      INET_URI(1, 1),
      /**
       * <code>TORRENT = 2;</code>
       */
      TORRENT(2, 2),
      ;

      /**
       * <code>BYTES = 0;</code>
       */
      public static final int BYTES_VALUE = 0;
      /**
       * <code>INET_URI = 1;</code>
       */
      public static final int INET_URI_VALUE = 1;
      /**
       * <code>TORRENT = 2;</code>
       */
      public static final int TORRENT_VALUE = 2;


      public final int getNumber() { return value; }

      public static PlayItemType valueOf(int value) {
        switch (value) {
          case 0: return BYTES;
          case 1: return INET_URI;
          case 2: return TORRENT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PlayItemType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<PlayItemType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PlayItemType>() {
              public PlayItemType findValueByNumber(int number) {
                return PlayItemType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final PlayItemType[] VALUES = values();

      public static PlayItemType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private PlayItemType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:open_audio.PlayItem.PlayItemType)
    }

    private int bitField0_;
    // optional bytes item_bytes = 1;
    public static final int ITEM_BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString itemBytes_;
    /**
     * <code>optional bytes item_bytes = 1;</code>
     */
    public boolean hasItemBytes() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes item_bytes = 1;</code>
     */
    public com.google.protobuf.ByteString getItemBytes() {
      return itemBytes_;
    }

    // optional string item_id = 2;
    public static final int ITEM_ID_FIELD_NUMBER = 2;
    private java.lang.Object itemId_;
    /**
     * <code>optional string item_id = 2;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string item_id = 2;</code>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string item_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string item_uri = 3;
    public static final int ITEM_URI_FIELD_NUMBER = 3;
    private java.lang.Object itemUri_;
    /**
     * <code>optional string item_uri = 3;</code>
     */
    public boolean hasItemUri() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string item_uri = 3;</code>
     */
    public java.lang.String getItemUri() {
      java.lang.Object ref = itemUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string item_uri = 3;</code>
     */
    public com.google.protobuf.ByteString
        getItemUriBytes() {
      java.lang.Object ref = itemUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes torrent_bytes = 4;
    public static final int TORRENT_BYTES_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString torrentBytes_;
    /**
     * <code>optional bytes torrent_bytes = 4;</code>
     */
    public boolean hasTorrentBytes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes torrent_bytes = 4;</code>
     */
    public com.google.protobuf.ByteString getTorrentBytes() {
      return torrentBytes_;
    }

    // optional .open_audio.PlayItem.PlayItemType play_type = 5;
    public static final int PLAY_TYPE_FIELD_NUMBER = 5;
    private org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType playType_;
    /**
     * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
     */
    public boolean hasPlayType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
     */
    public org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType getPlayType() {
      return playType_;
    }

    private void initFields() {
      itemBytes_ = com.google.protobuf.ByteString.EMPTY;
      itemId_ = "";
      itemUri_ = "";
      torrentBytes_ = com.google.protobuf.ByteString.EMPTY;
      playType_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType.BYTES;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, itemBytes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getItemUriBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, torrentBytes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(5, playType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, itemBytes_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getItemUriBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, torrentBytes_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, playType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.PlayItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bdawg.open_audio.OpenAudioProtos.PlayItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code open_audio.PlayItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bdawg.open_audio.OpenAudioProtos.PlayItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_PlayItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_PlayItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bdawg.open_audio.OpenAudioProtos.PlayItem.class, org.bdawg.open_audio.OpenAudioProtos.PlayItem.Builder.class);
      }

      // Construct using org.bdawg.open_audio.OpenAudioProtos.PlayItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        itemUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        torrentBytes_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        playType_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType.BYTES;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_PlayItem_descriptor;
      }

      public org.bdawg.open_audio.OpenAudioProtos.PlayItem getDefaultInstanceForType() {
        return org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance();
      }

      public org.bdawg.open_audio.OpenAudioProtos.PlayItem build() {
        org.bdawg.open_audio.OpenAudioProtos.PlayItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bdawg.open_audio.OpenAudioProtos.PlayItem buildPartial() {
        org.bdawg.open_audio.OpenAudioProtos.PlayItem result = new org.bdawg.open_audio.OpenAudioProtos.PlayItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemBytes_ = itemBytes_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.itemUri_ = itemUri_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.torrentBytes_ = torrentBytes_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.playType_ = playType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bdawg.open_audio.OpenAudioProtos.PlayItem) {
          return mergeFrom((org.bdawg.open_audio.OpenAudioProtos.PlayItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bdawg.open_audio.OpenAudioProtos.PlayItem other) {
        if (other == org.bdawg.open_audio.OpenAudioProtos.PlayItem.getDefaultInstance()) return this;
        if (other.hasItemBytes()) {
          setItemBytes(other.getItemBytes());
        }
        if (other.hasItemId()) {
          bitField0_ |= 0x00000002;
          itemId_ = other.itemId_;
          onChanged();
        }
        if (other.hasItemUri()) {
          bitField0_ |= 0x00000004;
          itemUri_ = other.itemUri_;
          onChanged();
        }
        if (other.hasTorrentBytes()) {
          setTorrentBytes(other.getTorrentBytes());
        }
        if (other.hasPlayType()) {
          setPlayType(other.getPlayType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bdawg.open_audio.OpenAudioProtos.PlayItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bdawg.open_audio.OpenAudioProtos.PlayItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes item_bytes = 1;
      private com.google.protobuf.ByteString itemBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes item_bytes = 1;</code>
       */
      public boolean hasItemBytes() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes item_bytes = 1;</code>
       */
      public com.google.protobuf.ByteString getItemBytes() {
        return itemBytes_;
      }
      /**
       * <code>optional bytes item_bytes = 1;</code>
       */
      public Builder setItemBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        itemBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes item_bytes = 1;</code>
       */
      public Builder clearItemBytes() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemBytes_ = getDefaultInstance().getItemBytes();
        onChanged();
        return this;
      }

      // optional string item_id = 2;
      private java.lang.Object itemId_ = "";
      /**
       * <code>optional string item_id = 2;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string item_id = 2;</code>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string item_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string item_id = 2;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_id = 2;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_id = 2;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        itemId_ = value;
        onChanged();
        return this;
      }

      // optional string item_uri = 3;
      private java.lang.Object itemUri_ = "";
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public boolean hasItemUri() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public java.lang.String getItemUri() {
        java.lang.Object ref = itemUri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          itemUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public com.google.protobuf.ByteString
          getItemUriBytes() {
        java.lang.Object ref = itemUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public Builder setItemUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public Builder clearItemUri() {
        bitField0_ = (bitField0_ & ~0x00000004);
        itemUri_ = getDefaultInstance().getItemUri();
        onChanged();
        return this;
      }
      /**
       * <code>optional string item_uri = 3;</code>
       */
      public Builder setItemUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        itemUri_ = value;
        onChanged();
        return this;
      }

      // optional bytes torrent_bytes = 4;
      private com.google.protobuf.ByteString torrentBytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes torrent_bytes = 4;</code>
       */
      public boolean hasTorrentBytes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes torrent_bytes = 4;</code>
       */
      public com.google.protobuf.ByteString getTorrentBytes() {
        return torrentBytes_;
      }
      /**
       * <code>optional bytes torrent_bytes = 4;</code>
       */
      public Builder setTorrentBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        torrentBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes torrent_bytes = 4;</code>
       */
      public Builder clearTorrentBytes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        torrentBytes_ = getDefaultInstance().getTorrentBytes();
        onChanged();
        return this;
      }

      // optional .open_audio.PlayItem.PlayItemType play_type = 5;
      private org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType playType_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType.BYTES;
      /**
       * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
       */
      public boolean hasPlayType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType getPlayType() {
        return playType_;
      }
      /**
       * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
       */
      public Builder setPlayType(org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        playType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .open_audio.PlayItem.PlayItemType play_type = 5;</code>
       */
      public Builder clearPlayType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        playType_ = org.bdawg.open_audio.OpenAudioProtos.PlayItem.PlayItemType.BYTES;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:open_audio.PlayItem)
    }

    static {
      defaultInstance = new PlayItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:open_audio.PlayItem)
  }

  public interface ElectionMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string node_id = 1;
    /**
     * <code>optional string node_id = 1;</code>
     */
    boolean hasNodeId();
    /**
     * <code>optional string node_id = 1;</code>
     */
    java.lang.String getNodeId();
    /**
     * <code>optional string node_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeIdBytes();

    // optional int32 offer = 2;
    /**
     * <code>optional int32 offer = 2;</code>
     */
    boolean hasOffer();
    /**
     * <code>optional int32 offer = 2;</code>
     */
    int getOffer();

    // optional int64 timestamp = 3;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();

    // optional .open_audio.ElectionMessage.ElectionMessageType type = 4;
    /**
     * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
     */
    org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType getType();
  }
  /**
   * Protobuf type {@code open_audio.ElectionMessage}
   */
  public static final class ElectionMessage extends
      com.google.protobuf.GeneratedMessage
      implements ElectionMessageOrBuilder {
    // Use ElectionMessage.newBuilder() to construct.
    private ElectionMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ElectionMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ElectionMessage defaultInstance;
    public static ElectionMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ElectionMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ElectionMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              offer_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType value = org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ElectionMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ElectionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.class, org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ElectionMessage> PARSER =
        new com.google.protobuf.AbstractParser<ElectionMessage>() {
      public ElectionMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ElectionMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ElectionMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code open_audio.ElectionMessage.ElectionMessageType}
     */
    public enum ElectionMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OFFER = 0;</code>
       */
      OFFER(0, 0),
      /**
       * <code>MASTER_HB = 1;</code>
       */
      MASTER_HB(1, 1),
      /**
       * <code>NOTIFY_ELECTION = 2;</code>
       */
      NOTIFY_ELECTION(2, 2),
      /**
       * <code>CLIENT_HB = 3;</code>
       */
      CLIENT_HB(3, 3),
      /**
       * <code>ELECT_END = 4;</code>
       */
      ELECT_END(4, 4),
      /**
       * <code>ELECT_CONFLICT = 5;</code>
       */
      ELECT_CONFLICT(5, 5),
      ;

      /**
       * <code>OFFER = 0;</code>
       */
      public static final int OFFER_VALUE = 0;
      /**
       * <code>MASTER_HB = 1;</code>
       */
      public static final int MASTER_HB_VALUE = 1;
      /**
       * <code>NOTIFY_ELECTION = 2;</code>
       */
      public static final int NOTIFY_ELECTION_VALUE = 2;
      /**
       * <code>CLIENT_HB = 3;</code>
       */
      public static final int CLIENT_HB_VALUE = 3;
      /**
       * <code>ELECT_END = 4;</code>
       */
      public static final int ELECT_END_VALUE = 4;
      /**
       * <code>ELECT_CONFLICT = 5;</code>
       */
      public static final int ELECT_CONFLICT_VALUE = 5;


      public final int getNumber() { return value; }

      public static ElectionMessageType valueOf(int value) {
        switch (value) {
          case 0: return OFFER;
          case 1: return MASTER_HB;
          case 2: return NOTIFY_ELECTION;
          case 3: return CLIENT_HB;
          case 4: return ELECT_END;
          case 5: return ELECT_CONFLICT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ElectionMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ElectionMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ElectionMessageType>() {
              public ElectionMessageType findValueByNumber(int number) {
                return ElectionMessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ElectionMessageType[] VALUES = values();

      public static ElectionMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ElectionMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:open_audio.ElectionMessage.ElectionMessageType)
    }

    private int bitField0_;
    // optional string node_id = 1;
    public static final int NODE_ID_FIELD_NUMBER = 1;
    private java.lang.Object nodeId_;
    /**
     * <code>optional string node_id = 1;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string node_id = 1;</code>
     */
    public java.lang.String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string node_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 offer = 2;
    public static final int OFFER_FIELD_NUMBER = 2;
    private int offer_;
    /**
     * <code>optional int32 offer = 2;</code>
     */
    public boolean hasOffer() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 offer = 2;</code>
     */
    public int getOffer() {
      return offer_;
    }

    // optional int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional .open_audio.ElectionMessage.ElectionMessageType type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType type_;
    /**
     * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
     */
    public org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType getType() {
      return type_;
    }

    private void initFields() {
      nodeId_ = "";
      offer_ = 0;
      timestamp_ = 0L;
      type_ = org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType.OFFER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, offer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, offer_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.bdawg.open_audio.OpenAudioProtos.ElectionMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code open_audio.ElectionMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.bdawg.open_audio.OpenAudioProtos.ElectionMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ElectionMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ElectionMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.class, org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.Builder.class);
      }

      // Construct using org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        offer_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType.OFFER;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bdawg.open_audio.OpenAudioProtos.internal_static_open_audio_ElectionMessage_descriptor;
      }

      public org.bdawg.open_audio.OpenAudioProtos.ElectionMessage getDefaultInstanceForType() {
        return org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.getDefaultInstance();
      }

      public org.bdawg.open_audio.OpenAudioProtos.ElectionMessage build() {
        org.bdawg.open_audio.OpenAudioProtos.ElectionMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.bdawg.open_audio.OpenAudioProtos.ElectionMessage buildPartial() {
        org.bdawg.open_audio.OpenAudioProtos.ElectionMessage result = new org.bdawg.open_audio.OpenAudioProtos.ElectionMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.offer_ = offer_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bdawg.open_audio.OpenAudioProtos.ElectionMessage) {
          return mergeFrom((org.bdawg.open_audio.OpenAudioProtos.ElectionMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bdawg.open_audio.OpenAudioProtos.ElectionMessage other) {
        if (other == org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          bitField0_ |= 0x00000001;
          nodeId_ = other.nodeId_;
          onChanged();
        }
        if (other.hasOffer()) {
          setOffer(other.getOffer());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bdawg.open_audio.OpenAudioProtos.ElectionMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bdawg.open_audio.OpenAudioProtos.ElectionMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string node_id = 1;
      private java.lang.Object nodeId_ = "";
      /**
       * <code>optional string node_id = 1;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string node_id = 1;</code>
       */
      public java.lang.String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string node_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeIdBytes() {
        java.lang.Object ref = nodeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string node_id = 1;</code>
       */
      public Builder setNodeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 1;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string node_id = 1;</code>
       */
      public Builder setNodeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }

      // optional int32 offer = 2;
      private int offer_ ;
      /**
       * <code>optional int32 offer = 2;</code>
       */
      public boolean hasOffer() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 offer = 2;</code>
       */
      public int getOffer() {
        return offer_;
      }
      /**
       * <code>optional int32 offer = 2;</code>
       */
      public Builder setOffer(int value) {
        bitField0_ |= 0x00000002;
        offer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 offer = 2;</code>
       */
      public Builder clearOffer() {
        bitField0_ = (bitField0_ & ~0x00000002);
        offer_ = 0;
        onChanged();
        return this;
      }

      // optional int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional .open_audio.ElectionMessage.ElectionMessageType type = 4;
      private org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType type_ = org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType.OFFER;
      /**
       * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
       */
      public org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType getType() {
        return type_;
      }
      /**
       * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
       */
      public Builder setType(org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .open_audio.ElectionMessage.ElectionMessageType type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = org.bdawg.open_audio.OpenAudioProtos.ElectionMessage.ElectionMessageType.OFFER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:open_audio.ElectionMessage)
    }

    static {
      defaultInstance = new ElectionMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:open_audio.ElectionMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_open_audio_ClientCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_open_audio_ClientCommand_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_open_audio_PlayItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_open_audio_PlayItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_open_audio_ElectionMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_open_audio_ElectionMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\nopen_audio\"\342\001\n\rClientCo" +
      "mmand\022=\n\rclient_action\030\001 \001(\0162&.open_audi" +
      "o.ClientCommand.ClientAction\022\022\n\nnew_volu" +
      "me\030\002 \001(\005\022\021\n\ttimestamp\030\003 \001(\003\022\"\n\004item\030\004 \001(" +
      "\0132\024.open_audio.PlayItem\"G\n\014ClientAction\022" +
      "\010\n\004PLAY\020\000\022\t\n\005PAUSE\020\001\022\010\n\004STOP\020\002\022\n\n\006VOLUME" +
      "\020\003\022\014\n\010DOWNLOAD\020\004\"\304\001\n\010PlayItem\022\022\n\nitem_by" +
      "tes\030\001 \001(\014\022\017\n\007item_id\030\002 \001(\t\022\020\n\010item_uri\030\003" +
      " \001(\t\022\025\n\rtorrent_bytes\030\004 \001(\014\0224\n\tplay_type" +
      "\030\005 \001(\0162!.open_audio.PlayItem.PlayItemTyp",
      "e\"4\n\014PlayItemType\022\t\n\005BYTES\020\000\022\014\n\010INET_URI" +
      "\020\001\022\013\n\007TORRENT\020\002\"\373\001\n\017ElectionMessage\022\017\n\007n" +
      "ode_id\030\001 \001(\t\022\r\n\005offer\030\002 \001(\005\022\021\n\ttimestamp" +
      "\030\003 \001(\003\022=\n\004type\030\004 \001(\0162/.open_audio.Electi" +
      "onMessage.ElectionMessageType\"v\n\023Electio" +
      "nMessageType\022\t\n\005OFFER\020\000\022\r\n\tMASTER_HB\020\001\022\023" +
      "\n\017NOTIFY_ELECTION\020\002\022\r\n\tCLIENT_HB\020\003\022\r\n\tEL" +
      "ECT_END\020\004\022\022\n\016ELECT_CONFLICT\020\005B\'\n\024org.bda" +
      "wg.open_audioB\017OpenAudioProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_open_audio_ClientCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_open_audio_ClientCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_open_audio_ClientCommand_descriptor,
              new java.lang.String[] { "ClientAction", "NewVolume", "Timestamp", "Item", });
          internal_static_open_audio_PlayItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_open_audio_PlayItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_open_audio_PlayItem_descriptor,
              new java.lang.String[] { "ItemBytes", "ItemId", "ItemUri", "TorrentBytes", "PlayType", });
          internal_static_open_audio_ElectionMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_open_audio_ElectionMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_open_audio_ElectionMessage_descriptor,
              new java.lang.String[] { "NodeId", "Offer", "Timestamp", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
